BUGFIX: display demands: -- commons-logging scope set to compile otherwise NoClassDefFoundError is thrown -- log4j.properties added to configure logging properly -- throw new UnsupportedOperationException removed from onFailure methods
git-svn-id: svn://46.137.95.166/poptavka@1024 61682b0c-635e-44ba-a85b-d27e7dc34134