MailServiceMock introduced to avoid using Mockito#mock in spring test profile.
Previous solution leads to NoClassDefFoundError when running the generateDtd maven goal.